server:
  port: 8090

spring:
  cloud:
    stream:
      bindings:
        myOutputBinding:
          destination: somequeue
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
